---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/sonarr"
    pull: yes
    networks:
      - name: docker_default
    ports:
      - "8989:8989"
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "/home/igor/mnt/sk-1000/Series:/sk-1000/Series"
      - "/home/igor/mnt/wd-1000/Series:/wd-1000/Series"
      - "/home/igor/mnt/es-500/Series:/es-500/Series"
      - "/home/igor/transmission-daemon/downloads:/downloads"
    restart_policy: unless-stopped
