---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Copy Nginx configuration
  template:
    src: default.j2
    dest: "/etc/nginx/sites-available/default"
    mode: 0644
  notify: reload nginx
