---
ansible_become_password: "{{ vault_ansible_become_password }}"
netdata_claim_token: "{{ vault_netdata_claim_token }}"
netdata_claim_rooms: "{{ vault_netdata_claim_rooms }}"
restic_backup_repository: "{{  ansible_user_dir  }}/mnt/sk-1000/restic_backups"
restic_backup_source_paths:
  sonarr: "{{ docker_dir }}/sonarr/Backups"
  radarr: "{{ docker_dir }}/radarr/Backups"
  prowlarr: "{{ docker_dir }}/prowlarr/Backups"
  plex: "{{ docker_dir }}/plex/"
  atuin: "{{ ansible_user_dir }}/.local/share/atuin"
