---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/radarr"
    pull: yes
    networks:
      - name: docker_default
    ports:
      - "7878:7878"
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "/home/igor/mnt/sk-1000/Filmes:/sk-1000/Filmes"
      - "/home/igor/mnt/wd-1000/Filmes:/wd-1000/Filmes"
      - "/home/igor/mnt/es-500/Filmes:/es-500/Filmes"
      - "/home/igor/transmission-daemon/downloads:/downloads"
    restart_policy: unless-stopped
